---
title: "Work Packages"
toc: true
toc-depth: 3
---

### WP1 - Youth and Ocean Climate: Literacy, Agency, and Empowerment

#### Team

-   Geneviève Therriault (Education)
-   Boris Worm (Biology and Ocean Literacy)
-   Joseph Malloch (Computer Science)
-   Kristin Poduska (Physics)

#### Summary

WP1 focuses on fostering ocean/climate literacy and agency for transformative action in youth audiences. Herein, we will build on ocean literacy gaps documented in a pan-Canadian Survey (Glithero et al., 2020), previous educational research at Dalhousie (Guest et al., 2015; Worm et al., 2021) and UQAR (Jeziorski & Therriault, 2018, 2019; Morin, Therriault, Bader & Dumont, 2021) and an existing ocean literacy platform established at Dalhousie University and the National Film Board (Ocean School). The proposed work package will address issues related to the climate-ocean interface through a new digital toolbox and interactive media library that empower youth to make deeper connections, tell their own stories, and transform their civic agency. The scope of WP1 is to engage youth in primary and secondary schools in the co-construction of knowledge and competencies with the intention of fostering their engagement and eco-citizenship agency regarding climate- and ocean-related issues, so that they are truly considered in decision-making and the search for solutions (Fielding et al. 2019). Going beyond this LRP, our WP1 also has financial links with Cluster 2.1 (ocean-based carbon removal solutions) and 2.2 (ocean-based carbon capture and storage) for HQP who will formalize information flow from this WP into other parts of TCA that are focused on carbon-removal technology development, which is an important area for public engagement (Satterfield et al., 2023). In this way, the educational research we build in WP1 can help inform the carbon-capture LRPs approach community engagement.

This work package will build and transform young people's awareness of the climate/ocean interface, but also empowering them to define their own priority actions through codesign of tools such as educational games, 3D drawings, and artistic platforms. Our team consists of researchers from three universities in Quebec and the Maritime provinces (UQAR, DAL and MUN) including educational sciences, computer sciences (human-computer interaction) and natural sciences (specifically marine biology and physics). Together, we aim to engage young people in primary and secondary schools in Quebec and Atlantic Canada to explore and act on issues related to the climate-ocean interface through a toolbox that empowers them to deeply understand their climate-ocean connections. A special effort will be made to work outside of urban centers and include rural schools, even those far from the ocean, and those located within or near first-nation reserves.

WP1.1. The first stage focuses on designing and administering bilingual questionnaires and carrying out focus group interviews with pupils to gather information on their perspectives, concerns, and engagement with ocean and climate-related issues. We will use well-known conceptual tools of relationship to knowledge (a concept close to social representations – Kalali et al., 2019; Therriault et al., 2018) and epistemic cognition (also known as epistemological beliefs or personal epistemology – Therriault et al., 2020). Two other concepts will be documented: eco-citizen engagement through the concepts of agency and personal efficacy, and sense of empowerment (Morin, Therriault & Bader, 2022). Finally, feelings of disempowerment and eco-anxiety about climate issues will be explored.

WP1.2. The second stage will involve prototyping an open-source “toolbox” of empowering media content, open-source software, and interactive technologies for engaging with ocean-climate data, models, and policy and testing it along with supporting learning tools in primary and secondary educational settings as part of a pilot study. Our team’s expertise in human-computer interaction (computer science) and multimedia ocean literacy education (through the Ocean School platform) will be applied to the curation of existing tools and the development of new tools to populate a “toolbox”, which accounts for orientations in national school curricula. While the makeup of the toolbox will be iteratively determined by the results of our phase 1 data and the demands of students, we anticipate that it will include different kinds of static and interactive media created by the Ocean School, videos on ocean connectivity, online resources, prototyping tools and platforms for sensing and data analysis/visualization, and software tools for artistic/game creation, web publishing, among others. This toolbox will be made up of everything young people deeply need for the achievement of an open pedagogy inspired by socio-constructivist and humanist educational theories (Raby & Viola, 2022). Learning sequences will be pilot-tested in various formal school settings in Quebec (Bas-Saint-Laurent region) and the Maritime provinces (Nova Scotia, New Brunswick, Prince Edward Island, and Newfoundland/ Large Research Project Guidelines Labrador) and will be designed based on the findings of WP1.1, but will also build on the needs of young people for self-discovery, which could go as far as young people instigating a research project related to the natural sciences or humanities, with the close involvement of researchers from other clusters related to themes 1, 2 or 3 of the TCA program (in collaboration with cluster 3.1). Young people will be encouraged to genuinely connect and interact with experts, but also with organizations, entrepreneurs, representatives, policymakers, and decision-makers to enact the transformative ambition of this research program. Dedicated HQP (funded through other Cluster LRPs (2.1 and 2.2), will identify where student/teacher questions have intersections with TCA research in other Cluster LRPs and how we can leverage information, data, methods, or expertise into the toolbox components described above.

WP1.3. Finally, in the third phase, we will administer bilingual questionnaires and focus group studies like those used for WP1.1, to examine in detail the effects of implementing such an open pedagogical design. The above-mentioned conceptual tools from WP1.1 will frame observations of certain transformations concerning their relationship to knowledge, their civic agency, and their sense of empowerment. Of course, our mixed methodology, combining both qualitative and quantitative approaches, will be adapted to reach our target audience, made up of young people in primary and secondary schools in Quebec and Atlantic Canada. During this step, we will continue to identify and nurture links between this WP and other TCA data, methods, and expertise to address questions raised by students/teachers and adapt the toolbox to help provide ideas for community/youth engagement in other parts of the TCA work.

### WP2 - Art for Expression and Action

#### Team

-   Rina Wehbe (Computer Science)
-   Mayra Donaji Barrera Machuca (Computer Science)
-   Derek Reilly (Computer Science)
-   Joseph Malloch (Computer Science)

#### Summary

WP2 will explore the use of art as a means of expression for climate action, as a vehicle for sharing and communicating with the public about ocean climate issues, and to facilitate exploratory learning about these issues. We explore the unique opportunities that new media art presents for transforming climate action, like curiosity about novel technologies, opportunities for self-expression, and alternative forms of data presentation, focusing on three key questions: 1) in what ways can new media art enhance expression and communication of concepts, attitudes, and emotions regarding ocean climate? 2) How can new media art provide pathways for the public to understand issues at the ocean climate nexus, and in so doing, how can new media art support and enhance data interfaces and scientific communication? And 3) what impacts do the creation and appreciation of new media art have on an individual’s sense of empowerment vis-à-vis climate action? Each subproject will produce interactive prototypes and visualization systems by following an iterative process of design, prototyping, and feedback. This research-through-design approach will generate insights into how to build effective public-facing new media applications that foster personal connections to issues of climate. It will also allow for the active participation of the different communities affected by these issues in the design process. In WP2.1 Thermal Devices: communicating ocean climate issues with temperature, we explore thermal feedback, a subset of haptic feedback as a mechanism for self-expression and informal communication about ocean climate issues. It is possible to create pen-like devices for Virtual Reality that use temperature as a medium: artists can then use these devices to assign temperatures to regions in a 3D or 2D virtual artwork or data visualization. The piece can then be explored using a thermal pen or glove: when a region or surface of the artwork is intersected, the device emits the corresponding temperature, generating sensations of heat and cool. A within-subjects comparative evaluation of a thermal pen-like device and traditional techniques for recording and visualizing climate data will further our understanding of how incorporating different sensory modalities can enhance the exploration of multivariate datasets, particularly ocean climate data. In WP2.2 An Evolving Psychogeography of our Ocean Climate, we will further develop our prototype called “The Psychogeographer’s Table”. The table consists of a wooden 3D representation of the Halifax harbour, upon which we can project historical, current, and predicted climate and population data. A holographic augmented reality layer is used to present 3D content above, beneath, or around the table’s surface. This layer can extend the geographic range of the table to include the nearby ocean and coastline. It can also present weather phenomena above the table surface, and bathymetry and ocean climate data below the table surface. Psychogeography involves the mapping of affective experience: in this subproject, we will deploy the table in a storefront in downtown Halifax and provide means for city residents to interact with the table from the street, and to associate their affective response to data and trends they uncover. These collected responses will be represented in their own layer, providing a “psychogeographic” representation of the local ocean climate. We will explore the benefits of the 3D augmented reality layer of the Psychogeographer’s Table for data understanding and recall, compared to projection on the wooden 3D surface, and content presentation on a 2D tabletop display. In WP2.3 The Climate Marquee, we will explore the use of an urban public display—in this case, a digital marquee on the awning of a former movie theatre—to communicate ways in which coastal communities are impacted by our changing oceans. The motif here is that of traditional urban marquees that present stock information, weather forecasts, event advertisements, etc. Presenting climate data via this medium serves as a form of detournement, unsettling and challenging the usual day-to-day considerations of modern urban life to include forecasts that connect the immediate to longer timespans and the local to larger regions. The marquee is located on Barrington Street, in downtown Halifax, a place with high pedestrian traffic. This will expand our participant pool to people of different backgrounds, rather than just university members, and make participation easily accessible by way of location, and not charging to experience them.

The Climate Marquee, a Thermal Device, and Psychogeographer’s Table will be used by New Media Art students under the supervision of Kim Morgan (collaborator, Nova Scotia College of Art & Design), producing an exhibit comprising a series of vignettes that can be explored by the public as they approach and interact with the exhibit at our downtown location. This field study, conducted in year 3 of phase 2, achieves three complementary goals: 1) it is a trial of the ability of our tools to support creative expression on issues of climate, 2) it allows us to gather qualitative and quantitative observations of how these tools promote public engagement, and 3) the created artistic works will inform the further evolution of these tools in Phase two into a suite that can be deployed at multiple sites and in different contexts. As part of our research, we will conduct a gender-basis and age-based analysis to identify the effect of our developed technologies towards changing the climate change perception in the population. Our designs will also consider the accessibility of the design to user groups who may have differing (dis)ability profiles, particularly for user groups with difficulty accessing novel technologies.

### WP3 - Empowerment and Public Action

#### Team

-   Émilie Morin (Education)
-   Anne Fauré (Marine Resource Management)
-   Rina Wehbe (Computer Science)

#### Summary

Since education is considered one of the most efficient ways to reduce greenhouse gas emissions (Bhowmik et al., 2020), we need to better use it in the resolution of the climate crisis. The main objective of the WP3 is to develop a strong sense of empowerment (Morin, 2021) for individuals and communities (mainly youth) around the ocean and climate nexus. This will be accomplished by understanding, measuring, and supporting empowerment and public action. WP3 will seek an enhanced understanding of policy entrepreneurs and their role in public action and citizen engagement, by transforming knowledge in feasible policies. Policy entrepreneurs are individuals or groups (NGOs, think tanks, etc.) who actively seek to influence the development, implementation, and impact of public policies with new ideas or policy alternatives (Kingdon, 1984; Minstrom, 2019). WP3 will also explore the role of agency in supporting policy change. WP3 and WP4 will work together to understand key policy players and their impact. We plan to start the project in September 2024 and end it in March 2028. The research will mainly take place in Rimouski and Gaspésie.

WP3.1. Education: Using the capabilities approach (Sen, 2010), we will describe the dimension of sense of empowerment and the conditions to develop it. The objective is to describe the capabilities needed to be empowered as individuals, and as communities (e.g. university communities, school communities, cities) in the face of climate change and other ocean environmental issues. It is also to describe how this can lead to Public Action. Two communities are targeted for this WP: UQAR community (joint project with the transformative hub) and a Gaspésie fishing community (joint project with the cluster 3.3). A qualitative/interpretative approach will be used to characterize the sense of empowerment and describe the capabilities lacking for climate action. Literature review (on empowerment, sense of empowerment, climate change education, ocean education, using a citational justice approach), theoretical and conceptual work (between education and public policies), surveys and explanation interviews (with students, youth, researchers, administrators, and other members of the communities) will be used to achieve the objectives of this theme.

WP3.2. Public policies: We are interested in the role of these leaders, also known as policy entrepreneurs (Petridou and Minstrom, 2021, Minstrom, 2019, Brouwer and Hutema, 2018, Kingdon,1984, 2011), who intervene in the emergence of solutions in relation to ocean climate and community issues and organised significant policy change. We adopt a pluralist approach to the role of the state, considering the role of multiple actors in the development of public policy. We want to understand how policy entrepreneurs participate in the co-construction of knowledge and empower citizens (link with WP4 and cluster 3.1). We will provide insight into their role as catalysts in decision-making processes at multiple levels of governance in Canada. Understanding their action strategies will be useful by giving tools for youth and other agents of change to build strong public policies. (1) The first stage will consist of a review of these entrepreneurs in North America. (2) The second stage will examine the knowledge and information mobilized by these leaders to propose change. (3) The third stage will examine the managerial and political skills mobilized by these actors: attributes, skills, strategies (Minstrom, 2019). To achieve this, we will carry out a literature review on the issue of policy entrepreneurs in relation to climate change and oceans. We will conduct in-depth case studies of some of these entrepreneurs. We will complement this with semi-structured interviews and a literature review of the grey literature associated with their register of action. An inductive and constructivist approach will be privileged, notably in the construction of a theoretical framework (between education and public policies).

WP3.3 Games 4 Change: We propose a game that will seek to empower individuals by teaching within the game strategies for affecting the local environment. Consider the following example scenario: ‘within the game world, the play approaches a stream. The stream is running but littered with garbage. The player notes that within the environment they use rocks and remove rope for their pack to make a net by following the instructions of the game to assemble a sinking barrier to clean the stream.’ The player applies what they have learnt to create a stream garbage net and deploy it in their community. The game has shown them how to do so, but also empowered them to do so. By using gameful and playful approaches to teaching, we allow players to increase efficacy and we hypothesize that this will increase empowerment (Annetta, 2008). Providing people the information, a walk-through example, and an associated narrative is meant to teach the mechanics and techniques that can be used in the community to improve the surrounding environment on an individual level. In addition, calls to action can include engaging with public policy and government, or learning how to participate in the climate transformation work of policy entrepreneurs.

### WP4 - Transforming Climate Policy Making and Implementation

#### Team

-   Sandra Toze (Information Science)
-   Isabelle Caron (Public Policy)
-   Bertrum MacDonald (Information Science)
-   Anne Fauré (Marine Resource Management)
-   Kristin Poduska (Physics)

#### Summary

The effects of climate change and the costs of destructive weather extremes are now widespread (European Environment Agency, 2023; World Meteorological Organization, 2024). However, in the face of this evidence, strategies and public policies to mitigate gravely deteriorating environmental conditions and biodiversity losses and to implement adaptation options are seriously lagging. The volume of information on climate and climate change subjects has rapidly spiraled upward since the early decades of the twentieth century following the discovery that rising global temperatures were primarily caused by carbon dioxide emissions (Dessler, 2022). Even setting aside a sizeable volume of inconsequential information, the growing body of credible evidence that could be expected to inform decisions about climate change seems to have limited or very slow uptake in public policy and practice.

Most policy decision-making processes are notoriously complex and “messy” (Gluckman, 2018). The arena of public policy decision-making at all levels of government is populated with many different actors and actions where information of many types and formats can support decision-making processes if it reaches decision-makers in a timely and suitable manner (SAPEA, 2019). Evidence (information) can be introduced at many different entry points in decision processes where credibility, relevance, legitimacy, and timeliness are key factors for enabling evidence to be effective (MacDonald et al., 2016; Mitchell et al., 2006). Most information transmission routes in decision processes are not straightforward as the pathways are often drawn out and convoluted with potentially numerous blockage points (Bogenschneider & Corbett, 2021; Cairney, 2016). To better understand this complexity, and the frequent disconnect between evidence and policy, WP4 will use mixed methodology to address the cluster questions given in Table 1 above. In WP4.1 we will investigate these questions through a series of four comparative case studies of municipal level decision-making and climate change policy. Through WP4.2 we will provide a forum for the most relevant, thought-provoking, and diverse work centered on these questions, collecting chapters for a new edition of Science/Policy for Effective Coastal and Ocean Management Book. WP4 will also work with Cluster 2.1 (Alkalinity Enhancement and Algal Biomass for carbon removal strategies, during Phase I of their research regarding stakeholder engagement and evidence uptake in public policy decision processes.

WP4.1. Transforming Climate Action at the Municipal Level – Case Studies of 4 Coastal Cities: Although research about evidence-informed decision-making and policy development has been pursued extensively in recent decades, much remains inadequately understood about the enablers and barriers to the uptake of evidence in research-policy interfaces. Despite being on the frontlines of the climate crisis (Baker et al., 2012), local communities have historically had limited input into climate adaptation decisions where climate issues are affecting all citizens – link with cluster 3.1 (Manuel & MacDonald, 2020; Yet et al., 2022). Municipal governments are critical actors in implementing climate change adaptation and resilience policies (Mees, 2017), but their authority to create and implement these policies is bound by provincial legislation (Good, 2021). Informing and implementing climate change adaptation policies in local governments remains a significant challenge and some have even questioned their credibility (Olazabal et al., 2019). Little research has been conducted on what enables and restricts the uptake of evidence in municipal decision-making, and the literature that currently exists focuses is limited in scope (Levesque et al., 2021). For example, it is unclear to what extent information use behaviour influences decision-making processes regarding climate policy at the local and municipal government levels. In response to this gap, the goal WP4.1 is to conduct case studies of coastal municipalities to better understand and recommend improvements to coastal climate policy decision processes. The case studies will investigate the following key questions: How are urban coastal municipalities considering evidence in the development of policy to respond and adapt to climate change? What are the key enablers and barriers in the uptake of research in these contexts? How can enablers be enhanced, and barriers be mitigated for both policy makers and researchers? These case studies will be designed based on a participatory method. We will start with the guiding questions outlined above and work with the staff of the municipal governments in each case study to co-create the research questions, confirm methodologies, and work together towards results. In this way we will aim to directly involve policy- and decision-makers in the project. Together we will work to provide policy ready recommendations. We acknowledge that municipalities exist within a multi-level government environment, and include a range of stakeholders including citizens, youth, activist groups, researchers, as well as policy- and decision-makers. This work begins with a recognition that evidence includes diverse forms of data, information and knowledge including – scientific, social science, humanities, local and Indigenous knowledges. WP4.1 will work closely with WP3, to examine the impact of Policy Entrepreneurs within municipal climate policy processes.

WP4.2. New Edition of Science/Policy for Effective Coastal and Ocean Management Book. The first edition of this book focused on providing an overview of key topics critical to understanding the challenges of communicating scientific information in coastal and ocean management. Much has changed since this book was published in 2016. A new edition, focusing on the role of effective coastal and ocean management in transformation climate action is planned. A goal of the book will be to highlight the increasing diversity and interdisciplinarity of researchers and practitioners in this field.

### WP5 - Ocean-Climate Research Production and Mobilization

#### Team

-   Philippe Mongeon (Information Science)
-   Stephen Brooks (Computer Science)
-   Émilie Morin (Education)

#### Summary

WP5 leverages bibliometrics methods, generative AI, and qualitative research approaches to address the overarching CFREF questions: “What knowledge is being produced, disseminated, and used, by whom?”, and “What perspectives are over- or under-represented in the knowledge produced and mobilized?”. It examines the global ocean-climate research landscape, measure the level of engagement with research outputs in social media, policy documents and the media, model the influence of external factors in the production, dissemination, and use of research, and develop tools to facilitate the engagement of educators with scientific literature and teaching material for curriculum development. The research projects and their objectives are detailed below. WP5.1 Mapping the ocean-climate research landscape possesses two primary objectives: 1) identifying scholarly literature around the role of oceans in relation to climate, and 2) determining the structure or areas of research within that corpus of literature through the identification of research clusters (e.g., topics, areas) and capturing or measuring the evolution of the structure of that knowledge over time. WP5.2. Measuring the mobilization of ocean-climate research will use dataset produced in WP5.1. to measure engagement with the scholarly literature on oceans and climate change in research, social media, news, policy, and education. This project will shed light on what knowledge is mobilized in different societal spheres and by different stakeholders. It will also provide key insights on the over or under representation of research areas/topics in engagement with research. WP5.3. Investigating the drivers of knowledge production and mobilization will seek to understand the mechanisms that drive knowledge production (WP5.1) and mobilization (WP5.2.), such as world events, top-down political action, social events. This will allow for a further examination of how topics drift or evolve over time. The project will also explore how Generative AI can predict the future of ocean-climate research through its past and present states. Additionally, inverse causality, or the inference of events (such as the COVID-19 pandemic) may be possible from looking at changes in the flow of knowledge. WP5.4 The mobilization of scientific research in educational settings will analyze the Atlantic Canadian syllabi’s connection with scientific research, to measure the over and under-representation of knowledge areas in scientific research used in syllabi, and to understand the scientific information seeking practices of educators with an experimental search interface as a field study instrument.
