project:
  type: manuscript

manuscript:
  article: index.qmd
    
format:
#  wordcount-html: 
#   wordcount-banner: true
  html:
    manuscript: true
    notebook-links: false
    embed-resources: false
    theme: default
    light: true
    mainfont: "Helvetica"
#  docx: default

categories:
  - Open Access
  - Databases
  - Language
  - Countries

# jats: default
# pdf: default

execute:
  freeze: false

editor: visual

