project:
  type: manuscript

manuscript:
  article: index.qmd
    
format:
  html:
    manuscript: true
    notebook-links: false
    embed-resources: false
    theme: default
    light: true
    mainfont: "Helvetica"
  docx: default

categories:
  - Science-Policy Interface

# jats: default
# pdf: default

execute:
  freeze: false

editor: visual

